### ISSUE TITLE
Joint Controllership Agreement

### ISSUE THREAD

**Issue by DomiKoch** [trustedshops-public/connect-app-connector#58]
### Description

Hi @Mhera17 ,

please integrate a URL in the connector Layer:

![image](https://github.com/trustedshops-public/connect-app-connector/assets/97980151/af491350-0bb2-4a89-937f-dc01a9070ce9)
https://www.figma.com/file/DSdBJkx4LmSH3bt5gkyHGg/branch/zHIhADvyw7WQzs2BBQmbXa/Next-Gen-Plugin?type=design&node-id=1887-6907&mode=design&t=FJ7q622gN5aFvRZK-0

Phrase Key:
URL: global.jointcontrollership.url
Text: global.jointcontrollership.text

Greetings
Dominik

**Comment by eburck** [comment]
Hi @Mhera17 , for whatever reason I cannot see the added Joint Controllership Agreement text/link in my tests:
![image](https://github.com/trustedshops-public/connect-app-connector/assets/5467488/2dd8a913-4aa4-4fd0-b589-c7153ab18e28)
What am I missing?

**Comment by Mhera17** [comment]
Hi @eburck . Thanks
yes, there is a missing code. It probably happens during rebasing.
I have added missing lines in this PR https://github.com/trustedshops-public/connect-app-connector/pull/74

**Comment by eburck** [comment]
checked and done.
