### ISSUE TITLE
Bug: connector version 2.0 not showing order status if allowsEstimatedDeliveryDate: 'false' 

### ISSUE THREAD

**Issue by eburck** [trustedshops-public/connect-app-connector#66]
### What happened?

Set 
useVersionNumberOfConnector: '2.0' AND
allowsEstimatedDeliveryDate: 'false' 

this will result in select lists in Review Invites tab not being clickable.

### Problem description

connector version 2.0 not showing order status if allowsEstimatedDeliveryDate: 'false' 

### Expected behaviour

value of allowsEstimatedDeliveryDate: 'false'  should have no impact if version 2.0 is initialized.

### Actual  behaviour

select lists in Review Invites tab not being clickable.

### Steps to Reproduce

Set 
useVersionNumberOfConnector: '2.0' AND
allowsEstimatedDeliveryDate: 'false' 

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by Mhera17** [comment]
done. https://github.com/trustedshops-public/connect-app-connector/pull/80

**Comment by eburck** [comment]
tested and merged
