### ISSUE TITLE
EVENTS.GET_AVAILABLE_PRODUCT_IDENTIFIERS is not getting fired?

### ISSUE THREAD

**Issue by eburck** [trustedshops-public/connect-app-connector#71]
### What happened?

We realized lately, that setting a subset of identifiers with EVENTS.GET_AVAILABLE_PRODUCT_IDENTIFIERS doesn't have any effect.
Always all three identifiers SKU, GTIN. MPN are visible in Widget configuration:
![image](https://github.com/trustedshops-public/connect-app-connector/assets/5467488/fb49695d-af96-4ec6-aa66-30dddf34337b)

### Problem description

It seems like EVENTS.GET_AVAILABLE_PRODUCT_IDENTIFIERS not getting fired.

1. 
State a subset of identifiers, e.g. 
const productIdentifiers = [
  { id: 'data-sku', name: 'SKU' },
  //{ id: 'data-gtin', name: 'GTIN' },
  // { id: 'data-mpn', name: 'MPN' },
]

2. 
open connector and go to "Widgets-Tab"

3. 
open settings details of a Widget of type "product reviews"

### Expected behaviour

only the subset of identifiers are visible and selectable in configuration

### Actual  behaviour

Always all three identifiers SKU, GTIN. MPN are visible in Widget configuration:

### Steps to Reproduce

1. 
State a subset of identifiers, e.g. 
const productIdentifiers = [
  { id: 'data-sku', name: 'SKU' },
  //{ id: 'data-gtin', name: 'GTIN' },
  // { id: 'data-mpn', name: 'MPN' },
]

2. 
open connector and go to "Widgets-Tab"

3. 
open settings details of a Widget of type "product reviews"

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by Mhera17** [comment]
Done.

https://github.com/trustedshops-public/connect-app-connector/pull/73
