### ISSUE TITLE
Styling issue on the new reviews tab

### ISSUE THREAD

**Issue by loh-michael** [trustedshops-public/connect-app-connector#75]
### What happened?

Hello @Mhera17 
We have just noticed that there is a styling issue with the new based on Order status functionality within the reviews tab. The words "product reviews" and "service reviews" are cut off from the dropdown selection next to them. 

![ES](https://github.com/trustedshops-public/connect-app-connector/assets/93378862/50717988-ae64-46dc-9828-1c5bb7df1cc9)

### Problem description

This problem exists for the following languages:

- German 
- Polish
- Dutch 
- Spanish 
- Italian 
- Portuguese 

The only languages where it is not cut off are English and French. 

### Expected behaviour

No more display issues with the languages listed above

### Actual  behaviour

Nothing. Only the translations from phrase to github were merged. More screenshots of the other languages: 
![PL](https://github.com/trustedshops-public/connect-app-connector/assets/93378862/2f621782-2445-4a92-a90d-02748f62b4d8)
![PT](https://github.com/trustedshops-public/connect-app-connector/assets/93378862/03d39d9b-7481-4424-934c-43ab31894c8a)
![DE](https://github.com/trustedshops-public/connect-app-connector/assets/93378862/4d024f23-0ec1-4e6a-97ba-844836986368)
![IT](https://github.com/trustedshops-public/connect-app-connector/assets/93378862/b9585732-318c-45d4-a741-b849e760c9e6)
![NL](https://github.com/trustedshops-public/connect-app-connector/assets/93378862/cca27a00-bff0-4056-b143-5cefd353d071)

### Steps to Reproduce

Install plugin on QA --> select one of the languages (see list above) --> Reviews tab

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by Mhera17** [comment]
done in https://github.com/trustedshops-public/connect-app-connector/pull/78

**Comment by eburck** [comment]
tested and merged
